version: '3'
services:
 mongo:
    container_name: mongo
    image: mongo
    volumes:
        - 'D:\home-automation\mongodb\:/etc/mongodb/config/'
        - 'D:\home-automation\mongodb\db:/data/db'
    ports:
        - '27017:27017'