# publish-nuget.yml
name: Publish NuGet Package on Push to Main

on:
  push:
    branches:
      - main

jobs:
  Package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0"

      - name: Set tag var
        id: vars
        run: echo "nugetver=$(date +%y.%m%d.%H)" >> $GITHUB_OUTPUT

      - name: Publish Nuget To Github
        uses: wahinekai/actions-publish-nuget@v3.0.1
        with:
          version: ${{ steps.vars.outputs.nugetver }}
          project-path: JournalApp.Common/JournalApp.Common.csproj
          solution-path: maNoir.JournalApp.sln
          nuget-feed-password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Publish Nuget To Nuget.org
        uses: wahinekai/actions-publish-nuget@v3.0.1
        with:
          version: ${{ steps.vars.outputs.nugetver }}
          project-path: JournalApp.Common/JournalApp.Common.csproj
          solution-path: maNoir.JournalApp.sln
          nuget-feed-name: mynugetorg
          nuget-feed-password: ${{ secrets.NUGETORG_TOKEN }}
          nuget-feed-url: https://www.nuget.org/api/v2/package
